[server]
private_key_path = "/path/to/private.key"
control_port = 3000
listen_port = 3001
peer_port_range = "3002..4000"

[[peers]]
label = "peer-1"
public_key = "<base-64 encoded Ed25519 public key>"

[[peers]]
label = "peer-2"
public_key = "<base-64 encoded Ed25519 public key>"
